from pathlib import Path
p=Path('/mnt/data/mofakha_work/server.js'); s=p.read_text()
# routes
s=s.replace("app.get('/games/family-feud/players',(_,r)=>r.sendFile(path.join(__dirname,'public','games','family-feud','players.html')));", "app.get('/games/family-feud/players',(_,r)=>r.sendFile(path.join(__dirname,'public','games','family-feud','players.html')));app.get('/games/mafia/',(_,r)=>r.sendFile(path.join(__dirname,'public','games','mafia','players.html')));app.get('/games/mafia/players',(_,r)=>r.sendFile(path.join(__dirname,'public','games','mafia','players.html')));")
# prefix and pub/broadcast
s=s.replace("const prefixes={family:'A',guess:'B',market:'C',bomb:'D',last:'E',bank:'F',million:'G'};", "const prefixes={family:'A',guess:'B',market:'C',bomb:'D',last:'E',million:'G',mafia:'M'};")
old="function pub(g){if(g.type==='family'){const teams=(g.teams||[]).map(t=>({...t,players:(g.players||[]).filter(p=>p.team===t.id).map(p=>({id:p.id,name:p.name,online:p.online!==false,status:p.online!==false?'online':(p.disconnectedAt&&Date.now()-p.disconnectedAt<DISCONNECT_GRACE_MS?'reconnecting':'away')}))}));return {...g,players:(g.players||[]).map(p=>({id:p.id,name:p.name,team:p.team,online:p.online!==false,disconnectedAt:p.disconnectedAt||null,status:p.online!==false?'online':(p.disconnectedAt&&Date.now()-p.disconnectedAt<DISCONNECT_GRACE_MS?'reconnecting':'away')})),teams,bank:undefined}}if(g.type==='guess')return null;if(g.type==='million')return pubMillion(g);return g}"
new=old+"\nfunction mafiaPublic(g,sid){const sock=io.sockets.sockets.get(sid),pid=sock?.data?.pid,host=g.hostId===pid;const me=g.players.find(p=>p.id===pid);const out={type:'mafia',code:g.code,phase:g.phase,phaseUntil:g.phaseUntil||0,players:g.players.map(p=>({id:p.id,name:p.name,alive:p.alive!==false,online:p.online!==false,status:p.online!==false?'online':'away',role:g.phase==='finished'?p.role:undefined})),config:g.config,myRole:me?.role,myAction:g.nightActions?.[pid]||g.votes?.[pid]||null,isHost:host,winnerText:g.winnerText||null};if(g.phase==='night'&&me?.role==='detective'&&g.investigationResults?.[pid]!==undefined)out.investigationResult=g.investigationResults[pid];if(g.phase==='vote'&&g.voteResults&&Date.now()>=g.phaseUntil)out.voteResults=g.voteResults;if(g.phase==='discussion'&&g.lastNightResult)out.lastNightResult=g.lastNightResult;return out}\nfunction broadcastMafia(g){const room=io.sockets.adapter.rooms.get(g.code);if(!room)return;for(const sid of room){const sock=io.sockets.sockets.get(sid);if(sock)io.to(sid).emit('state',mafiaPublic(g,sid))}persistGames()}"
s=s.replace(old,new)
s=s.replace("function broadcast(g){if(g.phase==='finished'&&!g.finishedAt)g.finishedAt=Date.now();", "function broadcast(g){if(g.phase==='finished'&&!g.finishedAt)g.finishedAt=Date.now();if(g.type==='mafia'){broadcastMafia(g);return}")
# add mafia room function before miniRoom
marker="function miniRoom(game,mode,maxRounds){"
mafia_func=r'''function mafiaRoom(){return {type:'mafia',code:makeCode('mafia'),mode:'players',players:[],hostId:null,phase:'lobby',config:{maxPlayers:8,mafiaCount:2,detectiveCount:1,doctorCount:1,jesterCount:0,revealRole:true,tieMode:'none',nightSec:30,discussionSec:90,voteSec:30},rolesAssigned:false,nightActions:{},votes:{},investigationResults:{},lastNightResult:null,winnerText:null,round:0,phaseUntil:0}}\n'''
s=s.replace(marker,mafia_func+marker)
# create branch
s=s.replace("if(game==='family')g=ffRoom(mode||'1',rounds);else if(game==='guess')", "if(game==='family')g=ffRoom(mode||'1',rounds);else if(game==='mafia')g=mafiaRoom();else if(game==='guess')")
# create mafia should add host player and respond
needle="const p=addPlayer(g,s,name,team);if(g.type==='guess'){if(!g.hostId)g.hostId=p.id;if(category&&p.id===g.hostId)g.category=category} s.emit('room:created',{code:g.code,role:'player',playerId:p.id,team:p.team,sessionToken:p.sessionToken});broadcast(g)});"
repl="const p=addPlayer(g,s,name,team);if(g.type==='mafia'){g.hostId=p.id;s.emit('room:created',{code:g.code,role:'player',playerId:p.id,team:p.team,sessionToken:p.sessionToken});broadcastMafia(g);return}if(g.type==='guess'){if(!g.hostId)g.hostId=p.id;if(category&&p.id===g.hostId)g.category=category} s.emit('room:created',{code:g.code,role:'player',playerId:p.id,team:p.team,sessionToken:p.sessionToken});broadcast(g)});"
s=s.replace(needle,repl)
# room join: disallow new after start and redirect doesn't matter
s=s.replace("const p=addPlayer(g,s,name,team,token);s.join(g.code);", "if(g.type==='mafia'&&g.phase!=='lobby'&&!token)return s.emit('errorMsg','اللعبة بدأت بالفعل');const p=addPlayer(g,s,name,team,token);s.join(g.code);")
# room sync/resume broadcasts mafia personalized
s=s.replace("if(g.type==='bomb')emitBombState(g,s.id);else emit('state',pub(g))", "if(g.type==='bomb')emitBombState(g,s.id);else if(g.type==='mafia')s.emit('state',mafiaPublic(g,s.id));else emit('state',pub(g))")
s=s.replace("if(g.type==='bomb'){emitBombState(g,s.id);broadcastBomb(g)}else{broadcast(g)}persistGames()", "if(g.type==='bomb'){emitBombState(g,s.id);broadcastBomb(g)}else if(g.type==='mafia'){broadcastMafia(g)}else{broadcast(g)}persistGames()")
s=s.replace("if(g.type==='bomb'){emitBombState(g,s.id);broadcastBomb(g)}else broadcast(g);persistGames()", "if(g.type==='bomb'){emitBombState(g,s.id);broadcastBomb(g)}else if(g.type==='mafia'){broadcastMafia(g)}else broadcast(g);persistGames()")
# insert handlers before last:submit
insert_at=" s.on('last:submit',({answer}={})=>{"
handlers=r'''
 s.on('mafia:config',cfg=>{const g=games.get(s.data?.game);if(!g||g.type!=='mafia'||g.phase!=='lobby'||g.hostId!==s.data?.pid)return;const n=(v,d,min,max)=>Math.max(min,Math.min(max,Number(v)||d));const c={maxPlayers:n(cfg.maxPlayers,8,4,20),mafiaCount:n(cfg.mafiaCount,2,1,20),detectiveCount:n(cfg.detectiveCount,1,0,20),doctorCount:n(cfg.doctorCount,1,0,20),jesterCount:n(cfg.jesterCount,0,0,20),revealRole:!!cfg.revealRole,tieMode:cfg.tieMode==='revote'?'revote':'none',nightSec:n(cfg.nightSec,30,10,120),discussionSec:n(cfg.discussionSec,90,15,300),voteSec:n(cfg.voteSec,30,10,120)};if(c.mafiaCount+c.detectiveCount+c.doctorCount+c.jesterCount>c.maxPlayers)return s.emit('errorMsg','عدد الأدوار أكبر من عدد اللاعبين');if(g.players.length>c.maxPlayers)return s.emit('errorMsg','عدد اللاعبين الحالي أكبر من العدد المحدد');g.config=c;broadcastMafia(g)});
 s.on('mafia:start',()=>{const g=games.get(s.data?.game);if(!g||g.type!=='mafia'||g.phase!=='lobby'||g.hostId!==s.data?.pid)return;const c=g.config;if(g.players.length!==c.maxPlayers)return s.emit('errorMsg','يجب اكتمال عدد اللاعبين أولًا');if(c.mafiaCount+c.detectiveCount+c.doctorCount+c.jesterCount>g.players.length)return s.emit('errorMsg','عدد الأدوار أكبر من عدد اللاعبين');let pool=[...g.players];for(let i=pool.length-1;i>0;i--){const j=crypto.randomInt(i+1);[pool[i],pool[j]]=[pool[j],pool[i]]}let k=0;pool.forEach(p=>{p.alive=true;p.role='citizen'});for(let i=0;i<c.mafiaCount;i++)pool[k++].role='mafia';for(let i=0;i<c.detectiveCount;i++)pool[k++].role='detective';for(let i=0;i<c.doctorCount;i++)pool[k++].role='doctor';for(let i=0;i<c.jesterCount;i++)pool[k++].role='jester';g.rolesAssigned=true;g.phase='role';g.phaseUntil=0;g.nightActions={};g.votes={};g.investigationResults={};broadcastMafia(g)});
 s.on('mafia:ackRole',()=>{const g=games.get(s.data?.game);if(!g||g.type!=='mafia'||g.phase!=='role')return;const alive=g.players.filter(p=>p.alive!==false);const a=g.acks||(g.acks={});a[s.data.pid]=true;if(alive.every(p=>a[p.id]))mafiaNight(g);broadcastMafia(g)});
 s.on('mafia:nightAction',({targetId}={})=>{const g=games.get(s.data?.game),p=g?.players.find(x=>x.id===s.data?.pid);if(!g||g.type!=='mafia'||g.phase!=='night'||!p||p.alive===false||g.nightActions[p.id]?.submitted)return;const target=g.players.find(x=>x.id===targetId&&x.alive!==false&&x.id!==p.id);if(!target)return;g.nightActions[p.id]={submitted:true,targetId:target.id};if(p.role==='detective')g.investigationResults[p.id]=target.role==='mafia';broadcastMafia(g)});
 s.on('mafia:vote',({targetId}={})=>{const g=games.get(s.data?.game),p=g?.players.find(x=>x.id===s.data?.pid);if(!g||g.type!=='mafia'||g.phase!=='vote'||!p||p.alive===false||g.votes[p.id])return;const target=g.players.find(x=>x.id===targetId&&x.alive!==false&&x.id!==p.id);if(!target)return;g.votes[p.id]=target.id;if(g.players.filter(x=>x.alive!==false).every(x=>g.votes[x.id]))mafiaResolveVote(g);broadcastMafia(g)});
 s.on('mafia:restart',()=>{const g=games.get(s.data?.game);if(!g||g.type!=='mafia'||g.hostId!==s.data?.pid||g.phase!=='finished')return;g.players.forEach(p=>{p.alive=true;p.role=undefined});g.rolesAssigned=false;g.phase='lobby';g.phaseUntil=0;g.nightActions={};g.votes={};g.investigationResults={};g.acks={};g.lastNightResult=null;g.winnerText=null;broadcastMafia(g)});
 function mafiaNight(g){g.phase='night';g.phaseUntil=Date.now()+g.config.nightSec*1000;g.nightActions={};g.votes={};g.investigationResults={};g.acks={};broadcastMafia(g);const until=g.phaseUntil;setTimeout(()=>{if(g.phase==='night'&&g.phaseUntil===until)mafiaResolveNight(g)},g.config.nightSec*1000+100)}
 function mafiaResolveNight(g){const alive=g.players.filter(p=>p.alive!==false),actions=g.nightActions||{};const kills=alive.filter(p=>p.role==='mafia').map(p=>actions[p.id]?.targetId).filter(Boolean);const targetIds=[...new Set(kills)];const victim=targetIds.length?g.players.find(p=>p.id===targetIds[0]&&p.alive!==false):null;const doctors=alive.filter(p=>p.role==='doctor').map(p=>actions[p.id]?.targetId).filter(Boolean);if(victim&&!doctors.includes(victim.id)){victim.alive=false;g.lastNightResult={victimId:victim.id,victimName:victim.name,victimRole:g.config.revealRole?victim.role:undefined}}else g.lastNightResult={victimId:null,victimName:null};if(mafiaCheckWin(g))return;g.phase='discussion';g.phaseUntil=Date.now()+g.config.discussionSec*1000;broadcastMafia(g);const until=g.phaseUntil;setTimeout(()=>{if(g.phase==='discussion'&&g.phaseUntil===until)mafiaStartVote(g)},g.config.discussionSec*1000+100)}
 function mafiaStartVote(g){g.phase='vote';g.phaseUntil=Date.now()+g.config.voteSec*1000;g.votes={};broadcastMafia(g);const until=g.phaseUntil;setTimeout(()=>{if(g.phase==='vote'&&g.phaseUntil===until)mafiaResolveVote(g)},g.config.voteSec*1000+100)}
 function mafiaResolveVote(g){if(g.phase!=='vote')return;const counts={};Object.values(g.votes||{}).forEach(id=>counts[id]=(counts[id]||0)+1);const max=Math.max(0,...Object.values(counts));const top=Object.keys(counts).filter(id=>counts[id]===max);if(!max||top.length!==1){if(g.config.tieMode==='revote'){g.phase='vote';g.phaseUntil=Date.now()+g.config.voteSec*1000;g.votes={};g.voteResults={};broadcastMafia(g);return}g.lastNightResult={victimId:null,voteTie:true};mafiaNight(g);return}const victim=g.players.find(p=>p.id===top[0]&&p.alive!==false);if(victim){victim.alive=false;if(victim.role==='jester'){g.phase='finished';g.winnerText='🤡 المهرج فاز!';g.finishedAt=Date.now();broadcastMafia(g);return}}if(mafiaCheckWin(g))return;mafiaNight(g)}
 function mafiaCheckWin(g){const alive=g.players.filter(p=>p.alive!==false),m=alive.filter(p=>p.role==='mafia').length,other=alive.length-m;if(m===0){g.phase='finished';g.winnerText='👥 المواطنون فازوا!';g.finishedAt=Date.now();broadcastMafia(g);return true}if(m>=other){g.phase='finished';g.winnerText='🔪 المافيا فازت!';g.finishedAt=Date.now();broadcastMafia(g);return true}return false}
'''
s=s.replace(insert_at,handlers+insert_at)
p.write_text(s)
